const StartingTenants = [
    {
      id: 1,
      status: "existing",
      //status: ["existing", "inprogress", "completed", "failed"],
      name: "John Doe",
      flavor: "Vanilla",
      licenseType: "Standard",
      expirationDate: "2024-12-31",
    },
    {
      id: 2,
      status: "completed",
      name: "Mary Jane",
      flavor: "Chocolate",
      licenseType: "Full",
      expirationDate: "2025-11-30",
    },
    {
      id: 3,
      status: "failed",
      name: "Jack Black",
      flavor: "Caramel",
      licenseType: "Full",
      expirationDate: "2025-08-14",
    },
    {
      id: 4,
      status: "existing",
      name: "Alice White",
      flavor: "Peach",
      licenseType: "Standard",
      expirationDate: "2024-12-12",
    },
    {
      id: 5,
      status: "existing",
      name: "Barry Brown",
      flavor: "Strawberry",
      licenseType: "Full",
      expirationDate: "2025-03-20",
    },
    {
      id: 6,
      status: "existing",
      name: "Millie Green",
      flavor: "Kiwi",
      licenseType: "Standard",
      expirationDate: "2025-11-25",
    },
    {
      id: 7,
      status: "existing",
      name: "Alexander Shultz",
      flavor: "Chocolate",
      licenseType: "Full",
      expirationDate: "2026-05-15",
    },
    {
      id: 8,
      status: "existing",
      name: "Katelin Chan",
      flavor: "Cherry",
      licenseType: "Full",
      expirationDate: "2025-09-17",
    },
    {
      id: 9,
      status: "existing",
      name: "Billie Maquire",
      flavor: "Blueberry",
      licenseType: "Full",
      expirationDate: "2025-07-07",
    },
    {
      id: 10,
      status: "existing",
      name: "Bradley Peters",
      flavor: "Banana",
      licenseType: "Full",
      expirationDate: "2026-10-01",
    },
  ];
  
  export default StartingTenants;