name: Run tests

on:
  pull_request:
    branches: ['master']

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 16.18

      - name: Install Dependencies
        run: npm ci
      - name: Run tests
        run: npm test